---
# Update Time: 2024-2-1 21:10
version: "3.4"

x-defines:
  service-common: &service-common-ref
    networks: [network_cluster]
    restart: on-failure
  env-common: &env-common-ref
    NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1}
    TZ: ${TZ:-Asia/Shanghai}    
  env-proxy: &env-proxy-ref
    HTTP_PROXY: ${OPENCLASH_HTTP_PROXY}
    HTTPS_PROXY: ${OPENCLASH_HTTP_PROXY}
    restart_policy:
      condition: on-failure
      delay: 5s      
  deploy-common: &deploy-common-ref
    mode: replicated
    replicas: 1
  placement-default: &placement-default-ref
    placement:
      constraints:
        - node.labels.type == vm
        - node.labels.business == true
  driver-common: &driver-common-ref
    type: nfs
    o: addr=${NFS_SERVER},rw,nfsvers=4

services:
  # ------------------------------------------------------------
  # NocoBase无代码业务系统
  # ------------------------------------------------------------
  nocobase:
    <<: *service-common-ref
    # image: nocobase/nocobase:0.21.0-alpha.16
    image: registry.cloudvalley.site:4/nocobase/nocobase:main
    environment:
      <<: *env-common-ref
      DB_LOGGING: ${DB_LOGGING}
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      LOCAL_STORAGE_BASE_URL: ${LOCAL_STORAGE_BASE_URL}
    volumes:
      - nfs_nocobase:/app/nocobase/storage
    logging:
      driver: fluentd
      options:
        tag: docker.business.nocobase
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.nocobase.rule=Host(`nocobase.${DOMAIN_SWARM}`,`nocobase.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.nocobase.entrypoints=websecure
        - traefik.http.routers.nocobase.service=nocobase
        - traefik.http.routers.nocobase.middlewares=cors-headers@file,auth,normal-chain@file
        - traefik.http.services.nocobase.loadbalancer.server.port=80
        - homepage.group=Application
        - homepage.name=云谷之家
        - homepage.icon=https://www.waylon.wang:4/images/services/nocobase.png
        - homepage.href=https://nocobase.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=NocoBase低代码系统
        - homepage.siteMonitor=http://nocobase
        - homepage.weight=10
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # NocoDB无代码表单系统
  # ------------------------------------------------------------
  nocodb:
    <<: *service-common-ref
    image: nocodb/nocodb:latest
    environment:
      <<: *env-common-ref
      NC_DB: ${NC_DB}
      NC_PUBLIC_URL: https://nocodb.${DOMAIN_SWARM}:${EXTERNAL_PORT}
    volumes:
      - nfs_nocodb:/usr/app/data
    logging:
      driver: fluentd
      options:
        tag: docker.business.nocodb
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.nocodb.rule=Host(`nocodb.${DOMAIN_SWARM}`,`nocodb.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.nocodb.entrypoints=websecure
        - traefik.http.routers.nocodb.service=nocodb
        - traefik.http.routers.nocodb.middlewares=auth,normal-chain@file
        - traefik.http.services.nocodb.loadbalancer.server.port=8080
        - homepage.group=Application
        - homepage.name=NocoDB
        - homepage.icon=https://www.waylon.wang:4/images/services/nocodb.png
        - homepage.href=https://nocodb.${DOMAIN_SWARM}:${EXTERNAL_PORT}/dashboard
        - homepage.description=NocoDB多维表格
        - homepage.siteMonitor=http://nocodb:8080
        - homepage.weight=11
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # Draw.io流程图系统
  # ------------------------------------------------------------
  drawio:
    <<: *service-common-ref
    image: jgraph/drawio:latest
    environment:
      <<: *env-common-ref
    volumes:
      - nfs_drawio:/usr/local/tomcat/webapps/draw/js
    logging:
      driver: fluentd
      options:
        tag: docker.business.drawio
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.drawio.rule=Host(`drawio.${DOMAIN_SWARM}`,`drawio.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.drawio.entrypoints=websecure
        - traefik.http.routers.drawio.service=drawio
        - traefik.http.routers.drawio.middlewares=auth,normal-chain@file
        - traefik.http.services.drawio.loadbalancer.server.port=8080
        - homepage.group=Application
        - homepage.name=Draw.io
        - homepage.icon=diagrams-net.png
        - homepage.href=https://drawio.${DOMAIN_SWARM}:${EXTERNAL_PORT}
        - homepage.description=Draw.io绘图
        - homepage.siteMonitor=http://drawio:8080
        - homepage.weight=12
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # Start Page业务导航页
  # ------------------------------------------------------------
  startpage:
    <<: *service-common-ref
    image: loganmarchione/docker-php-startpage:latest
    environment:
      <<: *env-common-ref
    volumes:
      - nfs_startpage:/var/www/html/user_includes
    logging:
      driver: fluentd
      options:
        tag: docker.business.startpage
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.startpage.rule=Host(`startpage.${DOMAIN_SWARM}`,`startpage.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.startpage.entrypoints=websecure
        - traefik.http.routers.startpage.service=startpage
        - traefik.http.routers.startpage.middlewares=auth,normal-chain@file
        - traefik.http.services.startpage.loadbalancer.server.port=80
        - homepage.group=Application
        - homepage.name=startpage
        - homepage.icon=hoobs.png
        - homepage.href=https://startpage.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=startpage
        - homepage.siteMonitor=http://startpage
        - homepage.weight=30
      <<: [*deploy-common-ref, *placement-default-ref]


networks:
  network_cluster:
    external: true

volumes:
  # NFS
  nfs_nocobase:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/business/nocobase/storage
  nfs_nocodb:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/business/nocodb/data
  nfs_drawio:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/business/drawio/data
  nfs_startpage:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/business/startpage
...            